 ## Netflix Movies and TV Shows

Imported Pandas and NumPy for data preprocessing.

import pandas as pd
import numpy as np

Loaded the Netflix dataset from CSV file into a Pandas DataFrame.

In [92]:
df = pd.read_csv("netflix_titles.csv")
df.head()  #It Inspect the first 5 records

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

After loading, I checked the dataset size using shape() to know how many rows and columns are present.

In [93]:
original_shape = df.shape
print("Before Cleaning:", original_shape)

Before Cleaning: (8807, 12)

I used info() to check the total number of records, column names, data types, and identify columns containing missing values.

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

I used isnull() to identify missing values in each column. Missing data reduces data quality and must be handled before analysis.

In [95]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

I found missing values in columns like director, cast, country and rating. Instead of deleting rows, I replaced missing values using fillna().

In [96]:
df["director"] = df["director"].fillna("Unknown")
df["cast"] = df["cast"].fillna("Not Available")
df["country"] = df["country"].fillna("Unknown")
df["rating"] = df["rating"].fillna("Not Rated")
df["duration"] = df["duration"].fillna("Unknown")

The date column also had missing values, so I filled those missing entries first before converting the column into date format.”

In [97]:
df["date_added"] = df["date_added"].fillna("January 1, 2000")#Handled missing values using fillna() to avoid data loss.

Verified that missing values were handled successfully using isnull().

In [98]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

After handling missing values, I checked duplicate rows using duplicated().

I removed duplicate rows using drop_duplicates() and checked the dataset shape again.

In [99]:
duplicates = df.duplicated().sum()#remove repeated records
print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

Removed duplicate rows and verified dataset size again.

In [100]:
df = df.drop_duplicates()
print("After Removing Duplicates:", df.shape)

After Removing Duplicates: (8807, 12)

Standardized text values to maintain consistency in dataset.

In [101]:
df["type"] = df["type"].str.lower()
df["country"] = df["country"].str.title()

Converted date format into consistent dd-mm-yyyy format.

In [102]:
# Convert date safely
df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)

# Fill dates that became invalid after conversion
df["date_added"] = df["date_added"].fillna(pd.Timestamp("2000-01-01"))

# Format date consistently
df["date_added"] = df["date_added"].dt.strftime("%d-%m-%Y")

In [103]:
print(df.isnull().sum())

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

Renamed column headers by converting into lowercase and removing spaces.(I cleaned column names by converting them into lowercase and replacing spaces with underscores.)

In [104]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

Performed final missing value check after cleaning process.

In [105]:
print("Final Missing Values:")
print(df.isnull().sum())

Final Missing Values:
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

print("Final Data Types:")
print(df.dtypes)

Verified final data types after preprocessing.

In [106]:
print("Final Data Types:")
print(df.dtypes)

Final Data Types:
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

Reviewed final cleaned dataset.

In [107]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,Dick Johnson Is Dead,Kirsten Johnson,Not Available,United States,25-09-2021,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,tv show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-09-2021,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,tv show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,24-09-2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,tv show,Jailbirds New Orleans,Unknown,Not Available,Unknown,24-09-2021,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-09-2021,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Exported final cleaned dataset for future analysis.

In [108]:
df.to_csv("cleaned_netflix_dataset.csv", index=False)

This project demonstrates how preprocessing improves data quality and prepares raw data for analysis or machine learning.